<?php

declare(strict_types=1);

namespace Drupal\ai_whatsapp_automation\Application\Webhook;

use Drupal\ai_whatsapp_automation\Application\Evolution\QRProvider;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Logger\LoggerChannelFactoryInterface;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\GuzzleException;
use Psr\Log\LoggerInterface;

/**
 * Sends provider responses generated by the conversation engine.
 */
final class ProviderMessageSenderService {

  /**
   * Conservative message body limit for WhatsApp/Twilio text sends.
   */
  private const MESSAGE_SEGMENT_LIMIT = 1400;

  /**
   * The logger channel.
   */
  private readonly LoggerInterface $logger;

  /**
   * Constructs a ProviderMessageSenderService object.
   */
  public function __construct(
    private readonly ClientInterface $httpClient,
    private readonly ConfigFactoryInterface $configFactory,
    private readonly EntityTypeManagerInterface $entityTypeManager,
    LoggerChannelFactoryInterface $loggerFactory,
    private readonly QRProvider $qrProvider,
    private readonly WhatsAppTextFormatter $textFormatter,
  ) {
    $this->logger = $loggerFactory->get('ai_whatsapp_automation');
  }

  /**
   * Sends a text response through the originating provider.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   *
   * @return array<string, mixed>
   *   Delivery result.
   */
  public function sendText(string $provider, array $message, string $text): array {
    $text = trim($text);
    if ($text === '') {
      return ['status' => 'skipped_empty_response'];
    }
    // Every provider below is WhatsApp, which does not render Markdown.
    $text = $this->textFormatter->format($text);

    return match ($provider) {
      'twilio' => $this->sendTwilio($message, $text),
      'cloud_api' => $this->sendCloudApi($message, $text),
      'evolution' => $this->sendEvolution($message, $text),
      default => ['status' => 'unsupported_provider'],
    };
  }

  /**
   * Sends an approved provider template for a business-initiated message.
   *
   * @param array<string, mixed> $message
   *   Normalized recipient and account data.
   * @param array<string, string> $variables
   *   Template variables keyed by their Twilio placeholder number.
   *
   * @return array<string, mixed>
   *   Delivery result.
   */
  public function sendTemplate(string $provider, array $message, string $content_sid, array $variables = []): array {
    if ($provider !== 'twilio') {
      return ['status' => 'unsupported_template_provider'];
    }

    return $this->sendTwilioTemplate($message, $content_sid, $variables);
  }

  /**
   * Sends a Twilio WhatsApp message.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   */
  private function sendTwilio(array $message, string $text): array {
    $credentials = $this->resolveTwilioCredentials($message);
    $account_sid = $credentials['account_sid'];
    $auth_token = $credentials['auth_token'];
    $from = $this->resolveTwilioFrom($message);
    $to = (string) ($message['phone'] ?? '');

    if ($account_sid === '' || $auth_token === '' || $from === '' || $to === '') {
      return ['status' => 'skipped_missing_configuration'];
    }

    $twilio_from = $this->prefixWhatsApp($this->normalizeTwilioPhone($from));
    $twilio_to = $this->prefixWhatsApp($this->normalizeTwilioPhone($to));

    return $this->sendTextSegments(
      'twilio',
      $this->splitText($text),
      static fn(string $segment): array => [
        'method' => 'POST',
        'url' => 'https://api.twilio.com/2010-04-01/Accounts/' . $account_sid . '/Messages.json',
        'options' => [
          'auth' => [$account_sid, $auth_token],
          'form_params' => [
            'From' => $twilio_from,
            'To' => $twilio_to,
            'Body' => $segment,
          ],
          'ai_whatsapp_context' => [
            'provider' => 'twilio',
            'from' => $twilio_from,
            'to' => $twilio_to,
          ],
        ],
      ]
    );
  }

  /**
   * Sends a Twilio Content API template through Programmable Messaging.
   *
   * @param array<string, mixed> $message
   *   Normalized recipient and account data.
   * @param array<string, string> $variables
   *   Template variables keyed by their Twilio placeholder number.
   */
  private function sendTwilioTemplate(array $message, string $content_sid, array $variables): array {
    $credentials = $this->resolveTwilioCredentials($message);
    $account_sid = $credentials['account_sid'];
    $auth_token = $credentials['auth_token'];
    $from = $this->resolveTwilioFrom($message);
    $to = (string) ($message['phone'] ?? '');
    $content_sid = trim($content_sid);

    if ($account_sid === '' || $auth_token === '' || $from === '' || $to === '' || $content_sid === '') {
      return ['status' => 'skipped_missing_configuration'];
    }

    $twilio_from = $this->prefixWhatsApp($this->normalizeTwilioPhone($from));
    $twilio_to = $this->prefixWhatsApp($this->normalizeTwilioPhone($to));
    $form_params = [
      'From' => $twilio_from,
      'To' => $twilio_to,
      'ContentSid' => $content_sid,
    ];
    if ($variables !== []) {
      $form_params['ContentVariables'] = json_encode($variables, JSON_THROW_ON_ERROR);
    }

    return $this->request('POST', 'https://api.twilio.com/2010-04-01/Accounts/' . $account_sid . '/Messages.json', [
      'auth' => [$account_sid, $auth_token],
      'form_params' => $form_params,
      'ai_whatsapp_context' => [
        'provider' => 'twilio',
        'from' => $twilio_from,
        'to' => $twilio_to,
      ],
    ]) + ['provider' => 'twilio', 'template_sid' => $content_sid];
  }

  /**
   * Resolves the Twilio WhatsApp sender for a message.
   *
   * Account-specific phone numbers support multi-number routing. The global
   * setting remains a fallback for legacy single-number installations.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   */
  private function resolveTwilioFrom(array $message): string {
    $account_phone = trim((string) ($message['account_phone'] ?? ''));
    if ($account_phone !== '') {
      return $account_phone;
    }

    return (string) $this->configFactory
      ->get('ai_whatsapp_automation.settings')
      ->get('twilio.whatsapp_number');
  }

  /**
   * Resolves credentials for the routed WhatsApp account with global fallback.
   *
   * @param array<string, mixed> $message
   *   Normalized message data.
   *
   * @return array{account_sid: string, auth_token: string}
   *   Credentials for the outbound request.
   */
  private function resolveTwilioCredentials(array $message): array {
    $config = $this->configFactory->get('ai_whatsapp_automation.settings');
    $credentials = [
      'account_sid' => (string) $config->get('twilio.account_sid'),
      'auth_token' => (string) $config->get('twilio.auth_token'),
    ];
    $account = $this->getMessageAccount($message);
    if (!$account instanceof ContentEntityInterface) {
      return $credentials;
    }

    $account_sid = trim((string) ($account->get('twilio_account_sid')->value ?? ''));
    $auth_token = trim((string) ($account->get('twilio_auth_token')->value ?? ''));
    if ($account_sid !== '' && $auth_token !== '') {
      return [
        'account_sid' => $account_sid,
        'auth_token' => $auth_token,
      ];
    }

    return $credentials;
  }

  /**
   * Loads the explicit account associated with an outbound message.
   *
   * @param array<string, mixed> $message
   *   Normalized message data.
   */
  private function getMessageAccount(array $message): ?ContentEntityInterface {
    $account_id = $message['whatsapp_account_id'] ?? NULL;
    if ($account_id === NULL || $account_id === '') {
      return NULL;
    }

    $account = $this->entityTypeManager
      ->getStorage('ai_whatsapp_account')
      ->load($account_id);

    return $account instanceof ContentEntityInterface ? $account : NULL;
  }

  /**
   * Sends a WhatsApp Cloud API message.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   */
  private function sendCloudApi(array $message, string $text): array {
    $config = $this->configFactory->get('ai_whatsapp_automation.settings');
    $access_token = (string) $config->get('whatsapp_cloud.access_token');
    $phone_number_id = (string) $config->get('whatsapp_cloud.phone_number_id');
    $to = (string) ($message['phone'] ?? '');

    if ($access_token === '' || $phone_number_id === '' || $to === '') {
      return ['status' => 'skipped_missing_configuration'];
    }

    return $this->sendTextSegments(
      'cloud_api',
      $this->splitText($text),
      static fn(string $segment): array => [
        'method' => 'POST',
        'url' => 'https://graph.facebook.com/v20.0/' . $phone_number_id . '/messages',
        'options' => [
          'headers' => [
            'Authorization' => 'Bearer ' . $access_token,
            'Content-Type' => 'application/json',
          ],
          'json' => [
            'messaging_product' => 'whatsapp',
            'to' => ltrim($to, '+'),
            'type' => 'text',
            'text' => [
              'preview_url' => FALSE,
              'body' => $segment,
            ],
          ],
          'ai_whatsapp_context' => [
            'provider' => 'cloud_api',
            'to' => $to,
          ],
        ],
      ]
    );
  }

  /**
   * Sends an Evolution API message.
   *
   * @param array<string, mixed> $message
   *   Normalized incoming message data.
   */
  private function sendEvolution(array $message, string $text): array {
    $config = $this->configFactory->get('ai_whatsapp_automation.settings');
    $instance = (string) ($message['account_phone'] ?? '');
    if ($instance === '') {
      $instance = (string) $config->get('evolution.instance_name');
    }
    $to = (string) ($message['phone'] ?? '');

    if ($instance === '' || $to === '') {
      return ['status' => 'skipped_missing_configuration'];
    }

    $results = [];
    foreach ($this->splitText($text) as $segment) {
      $result = $this->qrProvider->sendMessage($instance, $to, $segment);
      $results[] = $result;

      if (($result['success'] ?? FALSE) !== TRUE) {
        return [
          'status' => 'failed',
          'error' => (string) ($result['error'] ?? $result['status'] ?? 'Evolution API send failed.'),
          'segments' => count($results),
          'results' => $results,
        ];
      }
    }

    return [
      'status' => 'sent',
      'status_code' => $results[array_key_last($results)]['status_code'] ?? NULL,
      'body' => json_encode($results, JSON_THROW_ON_ERROR),
      'segments' => count($results),
      'results' => $results,
    ];
  }

  /**
   * Sends text segments through an HTTP provider.
   *
   * @param string[] $segments
   *   Message text segments.
   * @param callable(string): array{method: string, url: string, options: array<string, mixed>} $request_builder
   *   Builds request data for a segment.
   *
   * @return array<string, mixed>
   *   Delivery result.
   */
  private function sendTextSegments(string $provider, array $segments, callable $request_builder): array {
    $results = [];
    foreach ($segments as $segment) {
      $request = $request_builder($segment);
      $result = $this->request($request['method'], $request['url'], $request['options']);
      $results[] = $result;

      if (($result['status'] ?? '') !== 'sent') {
        return [
          'status' => 'failed',
          'provider' => $provider,
          'segments' => count($results),
          'results' => $results,
        ];
      }
    }

    $last_result = $results[array_key_last($results)] ?? [];

    return $last_result + [
      'status' => 'sent',
      'provider' => $provider,
      'segments' => count($results),
      'results' => $results,
    ];
  }

  /**
   * Splits long provider messages into deliverable text segments.
   *
   * @return string[]
   *   Text segments.
   */
  private function splitText(string $text): array {
    $text = trim($text);
    if (mb_strlen($text) <= self::MESSAGE_SEGMENT_LIMIT) {
      return [$text];
    }

    $segments = [];
    $remaining = $text;
    while (mb_strlen($remaining) > self::MESSAGE_SEGMENT_LIMIT) {
      $chunk = mb_substr($remaining, 0, self::MESSAGE_SEGMENT_LIMIT);
      $split_position = $this->findSplitPosition($chunk);

      $segments[] = trim(mb_substr($remaining, 0, $split_position));
      $remaining = trim(mb_substr($remaining, $split_position));
    }

    if ($remaining !== '') {
      $segments[] = $remaining;
    }

    return $segments;
  }

  /**
   * Finds a natural split position near the end of a chunk.
   */
  private function findSplitPosition(string $chunk): int {
    foreach (["\n\n", "\n", '. ', ' '] as $separator) {
      $position = mb_strrpos($chunk, $separator);
      if ($position !== FALSE && $position > (int) (self::MESSAGE_SEGMENT_LIMIT * 0.6)) {
        return $position + mb_strlen($separator);
      }
    }

    return self::MESSAGE_SEGMENT_LIMIT;
  }

  /**
   * Performs an HTTP request and normalizes the result.
   *
   * @param array<string, mixed> $options
   *   Guzzle request options.
   *
   * @return array<string, mixed>
   *   Normalized delivery result.
   */
  private function request(string $method, string $url, array $options): array {
    $context = is_array($options['ai_whatsapp_context'] ?? NULL)
      ? $options['ai_whatsapp_context']
      : [];
    unset($options['ai_whatsapp_context']);

    try {
      $response = $this->httpClient->request($method, $url, $options + ['timeout' => 15]);
    }
    catch (GuzzleException $exception) {
      $this->logger->error('Provider message send failed from @from to @to: @message', [
        '@from' => (string) ($context['from'] ?? ''),
        '@to' => (string) ($context['to'] ?? ''),
        '@message' => $exception->getMessage(),
      ]);

      return [
        'status' => 'failed',
        'error' => $exception->getMessage(),
      ];
    }

    return [
      'status' => 'sent',
      'status_code' => $response->getStatusCode(),
      'body' => (string) $response->getBody(),
      'from' => (string) ($context['from'] ?? ''),
      'to' => (string) ($context['to'] ?? ''),
    ];
  }

  /**
   * Ensures a Twilio WhatsApp address has the expected prefix.
   */
  private function prefixWhatsApp(string $phone): string {
    $phone = trim($phone);

    return str_starts_with($phone, 'whatsapp:') ? $phone : 'whatsapp:' . $phone;
  }

  /**
   * Normalizes phone input to the format Twilio expects for WhatsApp.
   *
   * Twilio channels in Mexico retain the mobile 1 after country code 52.
   * Account records imported without it would otherwise fail with error 63007.
   */
  private function normalizeTwilioPhone(string $phone): string {
    $phone = preg_replace('/^whatsapp:/i', '', trim($phone)) ?? '';
    $digits = preg_replace('/\D+/', '', $phone) ?? '';

    if (str_starts_with($digits, '52') && strlen($digits) === 12) {
      $digits = '521' . substr($digits, 2);
    }

    return $digits === '' ? '' : '+' . $digits;
  }

}
